### PR TITLE
Add A23 MF_Filters to config file

### PR DESCRIPTION
**Pull request by abigailbishop**

### CODE REVIEW

**Comment by marcomuzio** [comment]
Hi @abigailbishop , not sure if this is waiting on anything else on your end. It looks good to me. Maybe my only concern is the filters are pretty narrow in frequency. It wouldn't hurt to widen them slightly I think but maybe they're okay? We will see once we get to processing things!

**Comment by abigailbishop** [comment]
I'm not waiting on anything else but we inherited those filter widths from Myoungchul so I'm happy to start processing data then adjust them later if they seem too strict!

**Comment by marcomuzio** [comment]
Sounds good, I say merge away!

**Comment by abigailbishop** [comment]
Aye captain!

**Pull request merged**
