### PR TITLE
Adding HPol CP map

### PR DESCRIPTION
**Pull request by Mohammad-Neutrino**

### CODE REVIEW

**Comment by clark2668** [comment]
This looks great. I say merge! Can you also please update the L2 script so that we save it?

**Comment by Mohammad-Neutrino** [comment]
Thanks, yes, I made that PR already. It was simply adding just "pulser_h" flag in L2.py

**Comment by clark2668** [comment]
Okay, great!

**Comment by Mohammad-Neutrino** [comment]
[like]  Seikh, Mohammad Ful Hossain reacted to your message:
________________________________

**Pull request merged**
